'use client';
import {useCallback,useEffect,useState} from 'react';
import AdminShell from '@/components/admin/AdminShell';
import './pico-ai.css';
import BackgroundPicker from './BackgroundPicker';
async function api(path,method='GET',data){const r=await fetch(`/api/pico-ai/admin/${path}`,{method,headers:{'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error);return b;}
export default function Page(){
 const [data,setData]=useState(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('Overview'),[busy,setBusy]=useState(false),[pair,setPair]=useState(),[preview,setPreview]=useState('');
 const refresh=useCallback(async()=>{try{setData(await api('overview'));setError('');}catch(e){setError(e.message);}},[]);
 useEffect(()=>{void refresh();const id=setInterval(refresh,10000);return()=>clearInterval(id);},[refresh]);
 async function act(fn,message){setBusy(true);setError('');try{await fn();setNotice(message||'Saved');await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const event=data?.events[0], jobs=data?.jobs||[],unique=new Set(jobs.filter(j=>j.captured_at).map(j=>j.session_id));
 return <AdminShell activeSection="traditional-ai"><div className="pico-ai">
 <header className="pai-heading"><div><span className="pai-eyebrow">PICO AI / GUEST EXPERIENCES</span><h1>Traditional AI<br/>Cloth Change</h1><p>One screen. A new look. A moment to keep.</p></div><span className={`pai-mode ${event?.mode==='live'?'live':''}`}>{event?.mode==='live'?'● Live AI':'◌ Demo mode'}</span></header>
 <nav className="pai-tabs" aria-label="Experience sections">{['Overview','Screens','Photos','Settings','Testing'].map((x,i)=><button key={x} aria-current={tab===x?'page':undefined} className={tab===x?'selected':''} onClick={()=>setTab(x)}><span aria-hidden="true" className="pai-tab-number">0{i+1}</span>{x}</button>)}</nav>
 {error&&<p className="pai-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!data&&!error&&<div className="pai-loading" role="status"><span aria-hidden="true"/>Connecting to your screens…</div>}
 {data&&tab==='Screens'&&data.devices.length===0&&<p className="pai-empty">Your first screen starts here. Create a code below, then enter it in the Pico AI app.</p>}
 {data&&tab==='Photos'&&jobs.length===0&&<p className="pai-empty">A space for their next favourite photo. Completed moments will appear here after your first capture.</p>}
 {event&&tab==='Overview'&&<><div className="pai-stats">{[['Guest sessions',data.sessions],['Photos captured',jobs.filter(j=>j.captured_at).length],['Completed',jobs.filter(j=>j.completed_at).length],['Retakes',Math.max(0,jobs.filter(j=>j.captured_at).length-unique.size)],['Failed',jobs.filter(j=>j.status==='failed').length],['Download requests',jobs.reduce((n,j)=>n+j.download_requests,0)]].map(([label,value])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><section className="pai-card"><h2>{event.name}</h2><p>{event.paused?'New sessions are paused.':'Ready to welcome guests.'}</p><p>{event.generations} / {event.generation_limit} paid attempts · ${Number(event.reserved_usd).toFixed(2)} / ${Number(event.budget_usd).toFixed(2)} reserved allowance</p><small>Allowance uses a conservative $0.25 reservation per AI attempt, including uncertain or failed calls. This is not a Google invoice. Activity totals cover the latest 1,000 attempts.</small><div className="pai-actions"><button disabled={busy} onClick={()=>act(()=>api(`events/${event.id}`,'PATCH',{paused:!event.paused}))}>{event.paused?'Resume screens':'Pause new sessions'}</button><button className="secondary" disabled={busy} onClick={()=>act(()=>api(`events/${event.id}`,'PATCH',{reset:true}),'Screens will return to welcome on their next check.')}>Return screens to welcome</button></div></section></>}
 {event&&tab==='Screens'&&<><section className="pai-card"><h2>Connect a screen</h2><p>Open the APK, enter your Pico Stock HTTPS address, then pair using a code.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>setPair(await api('devices','POST',{name:f.get('name'),eventId:event.id})),'Pairing code ready');}}><label>Screen name<input name="name" required maxLength={80} placeholder="Poster screen 01"/></label><button disabled={busy}>Create pairing code</button></form>{pair&&<div className="pai-code"><strong>{pair.code}</strong><p>{pair.name} · valid for 10 minutes · one use</p></div>}</section><div className="pai-grid">{data.devices.map(d=><section className="pai-card" key={d.id}><h3>{d.name}</h3><p>{d.revoked?'Revoked':Date.now()-Date.parse(d.last_seen)<30000?'● Connected':'○ Offline / not paired'}</p><small>{d.last_seen?new Date(d.last_seen).toLocaleString():'Waiting for first connection'}</small><p>Android: {d.diagnostics.android||'Not reported'} · Camera: {d.diagnostics.camera||'Not tested'}</p><button className="secondary" disabled={busy||d.revoked} onClick={()=>{if(confirm(`Disconnect ${d.name}? It will need a new pairing code.`))void act(()=>api(`devices/${d.id}`,'DELETE'));}}>Revoke pairing</button></section>)}</div></>}
 {tab==='Photos'&&<section className="pai-card"><h2>Recent moments</h2><p>Private to the event team. Photos expire after 24 hours.</p><div className="pai-table"><table><thead><tr><th>Time</th><th>Mode</th><th>Status</th><th>Details</th><th>Actions</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td>{new Date(j.created_at).toLocaleString()}</td><td>{j.mode==='live'?'AI':'Demo'}</td><td>{j.status}</td><td>{j.error||'—'}</td><td>{j.status==='ready'&&<button className="secondary" onClick={()=>setPreview(`/api/pico-ai/admin/jobs/${j.id}/image`)}>View</button>}<button className="secondary" disabled={busy||j.status==='expired'||j.status==='cancelled'} onClick={()=>{if(confirm('Delete this photo and revoke its download link?'))void act(()=>api(`jobs/${j.id}`,'DELETE'),'Photo deleted');}}>Delete</button></td></tr>)}</tbody></table></div></section>}
 {event&&tab==='Settings'&&<section className="pai-card"><h2>Event settings</h2><form key={`${event.id}-${event.mode}-${event.generation_limit}-${event.low_motion}-${event.background_id}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>api(`events/${event.id}`,'PATCH',{name:f.get('name'),background_id:f.get('background'),mode:f.get('mode'),generation_limit:Number(f.get('limit')),budget_usd:Number(f.get('budget')),low_motion:f.get('motion')==='on'}));}}><label>Event name<input name="name" defaultValue={event.name} required maxLength={100}/></label><BackgroundPicker value={event.background_id}/><label>Processing<select name="mode" defaultValue={event.mode}><option value="mock">Demo — no paid image changes</option><option value="live">Live Google AI — uses event allowance</option></select></label><label>Maximum paid attempts<input type="number" name="limit" min="0" max="10000" defaultValue={event.generation_limit}/></label><label>AI allowance (USD)<input type="number" name="budget" min="0" max="10000" step="0.25" defaultValue={event.budget_usd}/></label><label className="pai-check"><input type="checkbox" name="motion" defaultChecked={event.low_motion}/> Reduce animation</label><p>Capture retention: up to 1 hour. Completed posters: 24 hours. Guest gallery is off.</p><button disabled={busy}>Save settings</button></form></section>}
 {tab==='Testing'&&<section className="pai-card"><h2>Before guests arrive</h2><ul><li>Google API: {data?.configured.google?'Key configured — live quota still requires a real test':'Not configured'}</li><li>Email: {data?.configured.email?'Credentials configured — delivery still requires a test':'Off'}</li><li>Public HTTPS photo address: {data?.configured.publicUrl?'Configured':'Needs PICO_AI_SITE_URL'}</li></ul><ol><li>Pair the Android screen and check the camera preview.</li><li>Complete a demo with touch, then with remote arrows and OK.</li><li>Scan the QR using a separate phone.</li><li>Enable Live AI for the capped pilot and inspect both outfits.</li><li>Unplug/reconnect the camera, interrupt Wi-Fi and restart the APK.</li><li>Confirm portrait crop, comfortable control height and result quality on the actual screen.</li></ol><button disabled={busy} className="secondary" onClick={()=>act(()=>api('cleanup','POST'),'Retention cleanup completed')}>Run retention cleanup</button></section>}
 {preview&&<div className="pai-modal" onClick={()=>setPreview('')}><section onClick={e=>e.stopPropagation()}><button onClick={()=>setPreview('')}>Close</button><img src={preview} alt="Private guest portrait"/><a href={preview} target="_blank" rel="noreferrer">Open / download photo</a></section></div>}
 </div></AdminShell>;
}
