'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import AdminShell from '@/components/admin/AdminShell';
import NamePoster from '@/components/nameArt/NamePoster';
import { NAME_ART_BACKGROUNDS, NAME_ART_DEFAULTS } from '@/lib/nameArt/config';
import './name-art-admin.css';
export default function Page(){
 const [data,setData]=useState(null),[config,setConfig]=useState(NAME_ART_DEFAULTS),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pair,setPair]=useState(null),[sample,setSample]=useState('FAISAL');
 async function api(path,options={}){const response=await fetch('/api/name-art/admin/'+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json'}});const value=await response.json();if(!response.ok)throw Error(value.error);return value;}
 async function load(){try{const value=await api('overview');setData(value);setConfig(value.settings);setError('');}catch(e){setError(e.message);}}
 // Load once so a background refresh cannot overwrite unsaved operator choices.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{load();},[]);
 async function action(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <AdminShell activeSection="name-art"><div className="na-admin"><header className="na-heading"><div><Link href="/admin/pico-ai">← Guest experiences</Link><span>03 / PERSONALISED NAME ART</span><h1>A name.<br/>A beautiful memory.</h1><p>Guests choose their design. A personal reveal. A keepsake to take home.</p></div><div className="na-actions"><a href="/name-art/tablet" target="_blank" rel="noreferrer">Open iPad ↗</a><a href="/name-art/screen" target="_blank" rel="noreferrer">Open poster screen ↗</a></div></header>
 {error&&<p className="na-alert" role="alert">{error}</p>}{notice&&<p className="na-notice" role="status">{notice}</p>}
 <div className="na-workspace"><section className="na-settings"><h2>01 · The resting National Day artwork</h2><p>Shown on the poster screen between guests. Guests now pick their own design on the iPad, so this setting governs the idle screen only.</p><div className="na-backgrounds">{NAME_ART_BACKGROUNDS.map(item=><button key={item.id} className={config.background===item.id?'selected':''} onClick={()=>setConfig({...config,background:item.id})} aria-pressed={config.background===item.id}><img src={item.src} alt=""/><span>{item.name}</span>{item.id==='pearls'&&<small>Recommended</small>}</button>)}</div><h2>02 · The screen rhythm</h2><div className="na-fields"><label>Reveal style<select value={config.motion} onChange={e=>setConfig({...config,motion:e.target.value})}><option value="reveal">Soft engraved reveal</option><option value="gentle">Gentle fade</option><option value="none">Still · no animation</option></select></label><label>Time per guest<select value={config.duration} onChange={e=>setConfig({...config,duration:Number(e.target.value)})}>{[8,12,18,25,35,45,60].map(n=><option key={n} value={n}>{n} seconds</option>)}</select></label><label>Grace after Finish<select value={config.finishGrace} onChange={e=>setConfig({...config,finishGrace:Number(e.target.value)})}>{[0,5,10,15,20,30].map(n=><option key={n} value={n}>{n===0?'Clear immediately':`${n} seconds`}</option>)}</select></label></div><label className="na-toggle"><input type="checkbox" checked={config.drift} onChange={e=>setConfig({...config,drift:e.target.checked})}/> Subtle floating light while waiting</label><label className="na-toggle"><input type="checkbox" checked={config.paused} onChange={e=>setConfig({...config,paused:e.target.checked})}/> Pause new guests and the screen</label><button className="na-primary" disabled={busy||!data} onClick={()=>action(async()=>{await api('settings',{method:'PATCH',body:JSON.stringify(config)});setNotice('Saved. Paired devices receive these settings automatically.');})}>Save experience settings</button>
 <h2>03 · Connect the devices</h2><p>The permanent code works on both devices, any number of times, and never expires — an unattended booth can reconnect itself with it. Save settings above after changing it.</p><div className="na-fields"><label>Permanent pairing code<input inputMode="numeric" maxLength={8} value={config.pairingCode} onChange={e=>setConfig({...config,pairingCode:e.target.value.replace(/\D/g,'')})} placeholder="Empty switches it off"/></label></div><p className="na-help">Anyone who knows this code can connect a device to the booth. Change it here if it is ever shared too widely.</p><p>One-use codes below stay available for a temporary device. Each expires in 10 minutes.</p><div className="na-actions">{['tablet','screen'].map(role=><button key={role} disabled={busy||!data} onClick={()=>action(async()=>setPair({...await api('pair',{method:'POST',body:JSON.stringify({role,label:role==='tablet'?'Name Art iPad':'Name Art poster screen'})}),role}))}>Pair {role==='tablet'?'iPad':'poster screen'}</button>)}</div>{pair&&<div className="na-pair" role="status"><small>ENTER ON THE {pair.role.toUpperCase()}</small><strong>{pair.code}</strong><span>One use · 10 minutes</span></div>}<p className="na-help">Android: open the poster screen in Chrome → Install app. iPad: open the entry page in Safari → Share → Add to Home Screen. Keep both devices online.</p>
 </section><aside className="na-preview"><span>LIVE STYLE PREVIEW · SAMPLE NAME</span><NamePoster name={sample} background={config.background} motion={config.motion} drift={config.drift}/><label>Preview name<input value={sample} maxLength={30} onChange={e=>setSample(e.target.value)}/></label><small>Green lettering, antique-gold edge and an engraved shadow. Downloads are 1536 × 2304 pixels.</small></aside></div>
 <section className="na-activity"><div className="na-activity-title"><h2>Paired devices & recent posters</h2><button onClick={()=>action(load)} disabled={busy}>Refresh</button></div><div className="na-devices">{data?.devices.filter(d=>!d.revoked).map(d=><div key={d.id}><strong>{d.label}</strong><span>{d.role==='tablet'?'iPad entry':'Poster screen'}</span><button onClick={()=>action(async()=>{await api(`devices/${d.id}`,{method:'DELETE'});await load();})}>Disconnect</button></div>)}{data&&!data.devices.some(d=>!d.revoked)&&<p>No devices paired yet.</p>}</div><div className="na-table-wrap"><table><thead><tr><th>Name</th><th>Status</th><th>Poster</th><th>Download QR</th></tr></thead><tbody>{data?.jobs.map(job=><tr key={job.id}><td>{job.name}</td><td>{job.status}</td><td>{['queued','showing','displayed'].includes(job.status)&&<a href={`/name-art/p/${job.shareToken}`} target="_blank" rel="noreferrer">Open poster ↗</a>}</td><td>{['queued','showing','displayed'].includes(job.status)&&<a href={`/api/name-art/poster/${job.shareToken}/qr`} download="Guest-poster-QR.svg">Download QR ↓</a>}</td></tr>)}</tbody></table></div>{data&&!data.jobs.length&&<p>Your first guest poster will appear here.</p>}<p className="na-help">Private links expire after 48 hours. Anyone holding a guest’s QR can open that poster.</p><button disabled={busy} onClick={()=>action(async()=>{const result=await api('cleanup',{method:'POST'});setNotice(`Expired poster cleanup complete (${result.expired}).`);await load();})}>Remove expired guest posters</button></section>
 </div></AdminShell>;
}
