// Fixed tender price list (unit_price_fils = BHD * 1000). Full event = BD 44,745.
export const CATEGORIES = [
    'Structures & Staging', 'Furniture', 'Branding & Decor', 'Audio Visual',
    'Stationery', 'Equipment (Rental)', 'Services',
];

export const FIXED_QTY_ITEM_NOS = new Set([1, 2, 3, 10, 15, 16, 18, 38]);
export function isQtyFixed(itemNo) { return FIXED_QTY_ITEM_NOS.has(itemNo); }

export const CATALOG = [
    { itemNo: 1, name: 'Main Backdrop (Banner)', description: '9.5m × 4m, CNC detailing, stickers, includes group photo steps', category: 'Structures & Staging', defaultQty: 1, unit: 'set', unitPriceFils: 1120000 },
    { itemNo: 2, name: 'Main Backdrop (Backwall)', description: '9.5m × 4m, CNC detailing, stickers', category: 'Structures & Staging', defaultQty: 1, unit: 'set', unitPriceFils: 700000 },
    { itemNo: 3, name: 'Platform (with Carpet)', description: 'Three-step platform, carpeted, suitable for flagpoles', category: 'Structures & Staging', defaultQty: 1, unit: 'set', unitPriceFils: 133000 },
    { itemNo: 4, name: 'Official Chair', description: 'Luxury leather chair with wheels', category: 'Furniture', defaultQty: 10, unit: 'nos', unitPriceFils: 50000 },
    { itemNo: 5, name: 'Delegate Armchairs', description: 'Leather armchairs', category: 'Furniture', defaultQty: 80, unit: 'nos', unitPriceFils: 15000 },
    { itemNo: 6, name: 'Head Table', description: 'Adjustable round table for up to 10 persons (if not provided by hotel)', category: 'Furniture', defaultQty: 1, unit: 'set', unitPriceFils: 2600000 },
    { itemNo: 7, name: 'Delegates Table', description: 'W=300cm×H=75cm×D=60cm, secretariat use (if not provided by hotel)', category: 'Furniture', defaultQty: 4, unit: 'nos', unitPriceFils: 60000 },
    { itemNo: 8, name: 'Side Table (Wooden)', description: 'W=50cm×H=65cm×D=60cm', category: 'Furniture', defaultQty: 10, unit: 'nos', unitPriceFils: 55000 },
    { itemNo: 9, name: 'Side Table (Standard)', description: 'W=50cm×H=65cm×D=60cm', category: 'Furniture', defaultQty: 40, unit: 'nos', unitPriceFils: 30000 },
    { itemNo: 39, name: 'Display Monitor Covers', description: 'Wooden, head table-matching finish', category: 'Furniture', defaultQty: 10, unit: 'nos', unitPriceFils: 60000 },
    { itemNo: 40, name: 'Small Bins', description: 'Small bins to be set next to each of the delegations head that will be sitting on the roundtable', category: 'Furniture', defaultQty: 10, unit: 'nos', unitPriceFils: 7500 },
    { itemNo: 10, name: 'Table-top Floral Arrangement', description: '3m diameter', category: 'Branding & Decor', defaultQty: 1, unit: 'set', unitPriceFils: 350000 },
    { itemNo: 11, name: 'Platform Flagpoles', description: 'Metal, 2.5m', category: 'Branding & Decor', defaultQty: 21, unit: 'nos', unitPriceFils: 60000 },
    { itemNo: 12, name: 'Platform Flags', description: '150cm × 90.5cm', category: 'Branding & Decor', defaultQty: 21, unit: 'nos', unitPriceFils: 85000 },
    { itemNo: 13, name: 'Table-top Flagpoles', description: 'Metal, 35 cm', category: 'Branding & Decor', defaultQty: 21, unit: 'nos', unitPriceFils: 6000 },
    { itemNo: 14, name: 'Table-top Flags', description: '27.5×15 cm', category: 'Branding & Decor', defaultQty: 21, unit: 'nos', unitPriceFils: 3000 },
    { itemNo: 25, name: 'Table-top Delegate Name Tag', description: 'Customized wooden name plate 40cm(W)×14cm(H), engraving + brushed matte finish', category: 'Branding & Decor', defaultQty: 16, unit: 'nos', unitPriceFils: 10000 },
    { itemNo: 26, name: 'Table-top Country Name Tag', description: 'Customized wooden name plate 40cm(W)×14cm(H), engraving + brushed matte finish', category: 'Branding & Decor', defaultQty: 20, unit: 'nos', unitPriceFils: 10000 },
    { itemNo: 15, name: 'LED Screens', description: '2.5m × 4m with wooden frame (or equivalent large display)', category: 'Audio Visual', defaultQty: 4, unit: 'sets', unitPriceFils: 840000 },
    { itemNo: 16, name: 'Lighting System', description: 'Full conference lighting system incl. moving head wash lights, cables, on-site operator', category: 'Audio Visual', defaultQty: 1, unit: 'set', unitPriceFils: 8300000 },
    { itemNo: 17, name: 'Audio Amplifier', description: 'Conference grade', category: 'Audio Visual', defaultQty: 2, unit: 'set', unitPriceFils: 258000 },
    { itemNo: 18, name: 'Speakers', description: 'Conference speakers', category: 'Audio Visual', defaultQty: 10, unit: 'nos', unitPriceFils: 95000 },
    { itemNo: 19, name: 'Conference Communication System – Display Monitors', description: '24-inch display synchronized to a larger main display', category: 'Audio Visual', defaultQty: 10, unit: 'nos', unitPriceFils: 45000 },
    { itemNo: 20, name: 'Conference Communication System – Microphones', description: 'Wired Bosch gooseneck mics + chairman mic, mixer, amplifier, speakers, on-site technician', category: 'Audio Visual', defaultQty: 20, unit: 'nos', unitPriceFils: 75000 },
    { itemNo: 21, name: 'Conference Communication System – Wi-Fi', description: '~50 Mbps, up to 40 concurrent connections, for the duration of the meetings', category: 'Audio Visual', defaultQty: 5, unit: 'nos', unitPriceFils: 1420000 },
    { itemNo: 22, name: 'ID Badges', description: 'Smart card size', category: 'Stationery', defaultQty: 200, unit: 'nos', unitPriceFils: 3500 },
    { itemNo: 23, name: 'Lanyards', description: 'Black', category: 'Stationery', defaultQty: 200, unit: 'nos', unitPriceFils: 2800 },
    { itemNo: 24, name: 'Desk Pads (Leather)', description: 'Black leather desk pads', category: 'Stationery', defaultQty: 20, unit: 'nos', unitPriceFils: 35000 },
    { itemNo: 27, name: 'A4 Paper', description: 'Plain (per piece — evaluation basis)', category: 'Stationery', defaultQty: 5000, unit: 'pcs', unitPriceFils: 15 },
    { itemNo: 28, name: 'A4 Letterheads', description: 'With logo (per piece)', category: 'Stationery', defaultQty: 500, unit: 'pcs', unitPriceFils: 440 },
    { itemNo: 29, name: 'Notebooks A4 (Notepad)', description: 'With logo (per piece)', category: 'Stationery', defaultQty: 100, unit: 'pcs', unitPriceFils: 3000 },
    { itemNo: 30, name: 'Notebooks A5 (Spiral)', description: 'With logo (per piece)', category: 'Stationery', defaultQty: 100, unit: 'pcs', unitPriceFils: 2200 },
    { itemNo: 31, name: 'Folders with One Pocket (Printed)', description: 'With logo (per piece)', category: 'Stationery', defaultQty: 50, unit: 'pcs', unitPriceFils: 7800 },
    { itemNo: 32, name: 'Folders (Clear)', description: 'Without logo (per piece)', category: 'Stationery', defaultQty: 50, unit: 'pcs', unitPriceFils: 300 },
    { itemNo: 33, name: 'Desk Pads (Table Size)', description: 'W=65cm×H=41cm, Tan leather', category: 'Stationery', defaultQty: 20, unit: 'nos', unitPriceFils: 35000 },
    { itemNo: 34, name: 'Pen', description: 'Blue ink pens for the roundtable', category: 'Stationery', defaultQty: 10, unit: 'nos', unitPriceFils: 10000 },
    { itemNo: 35, name: 'Laptops (Rental Basis)', description: '16GB RAM, 13th Gen Ryzen 3 8300GE, 256GB SSD', category: 'Equipment (Rental)', defaultQty: 5, unit: 'nos', unitPriceFils: 35000 },
    { itemNo: 36, name: 'Color Laser Printer (Rental Basis)', description: 'A4/A3 all-color, incl. papers, delivery, setup, on-site support (Print/Copy/Scan)', category: 'Equipment (Rental)', defaultQty: 1, unit: 'nos', unitPriceFils: 420000 },
    { itemNo: 37, name: 'Photocopiers (Rental Basis)', description: 'Multifunction B&W + color, 30-45 ppm, auto-stapling, delivery/setup/support', category: 'Equipment (Rental)', defaultQty: 3, unit: 'nos', unitPriceFils: 130000 },
    { itemNo: 38, name: 'Event Management Staff', description: 'Services of Event Project Manager, Project & Production Coordinators (4-5 pax). Technical personnel included in respective AV sections.', category: 'Services', defaultQty: 1, unit: 'pax', unitPriceFils: 1000000 },
];
