// Per-item scope breakdown (main line + indented sub-lines) matching PICO's
// issued GCC-meeting quotations. Keyed by tender item number.
export const ITEM_DETAILS = {
    1: { mainDesc: 'Backwall MDF structure.  Size: 9.5m*H4m', subs: [
        { label: 'Structure:', desc: 'Wooden platform (2 step) with carpet.  Size: L9.5*D(1.2+0.6)m*H0.2m', qty: '1' },
        { label: 'Graphic:', desc: 'Print and install graphic for backdrop.  Size: 9.5m*4m', qty: '38', unit: 'sqm' },
    ] },
    2: { mainDesc: 'Backwall MDF structure.  Size: 9.5m*H4m', subs: [
        { label: 'Logo:', desc: 'Logo in MDF base in spray paint finish.', qty: '1' },
        { label: 'Name plate:', desc: 'Wall mount plate for print of meeting name', qty: '1' },
    ] },
    3: { mainDesc: 'Custom built for Group Photo', subs: [{ desc: 'Wooden platform with carpet finish.  Size: 9.5m*2m', qty: '19', unit: 'sqm' }] },
    4: { mainDesc: '(rental supply from standard inventory)', subs: [{ desc: 'High-back executive leather chair with arms and base with castors' }] },
    5: { mainDesc: '(rental supply from standard inventory)', subs: [{ desc: 'Leather armchairs with wooden legs' }] },
    6: { mainDesc: 'Custom built', subs: [{ desc: 'Round configuration modular table for 10 (adjustible for 7-10 pax with custom filler pieces). Structure constructed in MDF with wood veneer finish, CNC/inlay decorative elements on top, including provision for cable management & display screen mounting. Overall size: Ø6680mm*H780mm (for 10 pax)' }] },
    7: { scope: 'Secretariat Table', mainDesc: 'Wooden desk MDF structure, with worktop & skirting panel (front & sides).  Size: 300*60cm*H75cm' },
    8: { mainDesc: 'For Head of Delegates', subs: [{ desc: 'MDF Structure. Size: 50cm*60cm*H65cm' }] },
    9: { mainDesc: 'For Delegates', subs: [{ desc: 'Wooden base in MDF veneer finish with tempered glass top. Size: 50cm*60cm*H65cm' }] },
    10: { mainDesc: 'Table centrepiece floral arrangement (based on artificial flowers/leaves for multi-use). Size: 3mØ' },
    11: { mainDesc: '(rental supply from standard inventory)', subs: [{ desc: 'Floor standing flagpole kit (2.5m pole, weighted base) with standard finiale, all in gold finish.  Overall H2.5m' }] },
    12: { mainDesc: 'Custom print', subs: [{ desc: 'Double sided fabric printed flags with internal stiffener material.  Size: 150cm x 90.5cm' }] },
    13: { mainDesc: '(rental supply from standard inventory)', subs: [{ desc: 'Metal desktop flagpole - single pole with base.  Gold colour.  Pole & finiale: H40cm, base 90cmDia*H2.5cm' }] },
    14: { mainDesc: 'Custom print', subs: [{ desc: 'Double-sided fabric flags.  Size: 22cm*15cm' }] },
    15: { mainDesc: '(rental supply from standard inventory)', subs: [
        { label: 'Screen:', desc: 'LED Pixel Pitch: P2.9.  Screen size: 4m x H2.5m', qty: '40', unit: 'sqm' },
        { desc: 'LED Processor (NOVASTAR J6) & Lightware matrix', qty: '1', unit: 'set' },
        { desc: 'Power & data cables, mounting accessories', qty: '1', unit: 'ls' },
        { label: 'Frame:', desc: 'Custom built wooden cladding for screen base, sides and top frame', qty: '4', unit: 'sets' },
        { label: 'Logistics:', desc: 'Transport & delivery, labour for installation, dismantling, including storage between events', qty: '1', unit: 'x' },
        { label: 'Technical services:', desc: 'Services of LED technician for installation, programming, operation during event', qty: '1', unit: 'pax' },
    ] },
    16: { mainDesc: '(rental supply from standard inventory)', subs: [
        { label: 'Lights:', desc: 'LED Profile Source Four LED Series 2 Lustr, with 26/36° lens', qty: '30', unit: 'nos' },
        { desc: 'ROBE Spiiders', qty: '38', unit: 'nos' },
        { label: 'Control:', desc: 'AVOLITE lighting console', qty: '1', unit: 'set' },
        { label: 'Accessories:', desc: 'Truss & rigging gear, cables', qty: '1', unit: 'lot' },
        { label: 'Technical services:', desc: 'Services of Lighting operator & technician for installation, programming, operation during event (provision for 3 days)', qty: '2', unit: 'pax' },
    ] },
    17: { mainDesc: '(Audio System - rental supply from standard inventory)' },
    18: { scope: 'Speaker System', mainDesc: '(Audio System - rental supply from standard inventory)' },
    19: { subs: [{ desc: 'Flat 24-inch FHD display monitor' }, { desc: 'HDMI cables for connection' }] },
    20: { subs: [
        { desc: '(rental supply from standard inventory)' },
        { desc: 'Tabletop conference system - wired unit with gooseneck microphone including power supply, switch, cabling', qty: '9', unit: 'nos' },
        { desc: 'Technician for installation and event operation', qty: '1', unit: 'pax' },
    ] },
    25: { mainDesc: 'Custom built', subs: [{ desc: 'Custom name plate - wooden table-top stand with metal plate with text engraving.  Size: 40cm*H14cm' }] },
    26: { mainDesc: 'Custom built', subs: [{ desc: 'Custom name plate - wooden table-top stand with metal plate with text engraving.  Size: 40cm*H14cm' }] },
    27: { mainDesc: 'Based on 500 pcs/reem', subs: [{ desc: 'Plain A4 paper. 80 gsm.' }] },
    28: { mainDesc: 'Custom offset print; based on MoQ of 500 pcs', subs: [{ desc: 'Size: A4, Material 115 gsm Favini Excellentia Extreme White (as per availability). Printing: 1 x 0 Color, bottom pattern, gold colour foiling logo on top.' }] },
    29: { mainDesc: 'Based on MoQ of 100 pcs', subs: [{ desc: 'Note Pad: Cover 250 gsm matt, logo gold foiling + matt lamination on outer side, inside 70 gsm cream dairy paper, 4 x 0 color printing (same artwork on all pages), making pads (top) of 50 sheets each.' }] },
    30: { mainDesc: 'Based on MoQ of 100 pcs', subs: [{ desc: 'Spiral Note Book: Cover 350 gsm matt + logo printing + matt lamination on outer side, inside 70 gsm cream dairy paper, 1 x 0 color printing (same artwork on all pages), spiral binding (top) of 50 sheets each.' }] },
    31: { scope: 'Folders (Printed)', mainDesc: 'Based on MoQ of 50 pcs', subs: [{ desc: 'Fit to A4 sheets, 4 x 0 col. printing, 350 gsm art matt + matt lamination on outer side, gold col. foiling logo & border on front side, die cutting & fabricated to folder with pocket.' }] },
    32: { mainDesc: 'Clear folder to fit A4 sheets, size 22 x 31 cm closed (w x h). As per local availability.' },
    33: { mainDesc: 'Tan leather', subs: [{ desc: 'Size 65 x 41 cm (w x h). Available colour PU material, 2000 gsm gray board pasted double, thread stitching on all sides & fabrication.' }] },
    34: { mainDesc: 'Blue ink pens suitable for Ministerial meeting to be placed on the roundtable' },
    36: { mainDesc: 'A3 / Functions Print, Copy & Scan, Hi-Speed USB 2.0, Gigabit Ethernet Network, up to 1200 x 1200 dpi, up to 46 ppm black and colour, laser printer', subs: [{ desc: 'Provision for one set of toners (CMYK)', qty: '1', unit: 'set' }] },
    38: { mainDesc: 'Services of Event Project Manager, Project & Production Coordinators (4-5 pax)', subs: [{ desc: 'NOTE: Technical personnel included in respective AV sections' }] },
    39: { mainDesc: 'Custom built', subs: [{ desc: 'Provision for custom cover (MDF, wood veneer finish) for table-top 24" display screen' }] },
    40: { mainDesc: 'Small bins to be set next to each of the delegations head that will be sitting on the roundtable' },
};

export function itemDetail(itemNo) { return ITEM_DETAILS[itemNo]; }
