export const LANDMARK_SCAN_CATALOG = [
  ['ksa-at-turaif-diriyah', 'At-Turaif, Diriyah', 'Saudi Arabia'],
  ['ksa-salwa-palace', 'Salwa Palace', 'Saudi Arabia'],
  ['ksa-al-masmak-fortress', 'Al Masmak Fortress', 'Saudi Arabia'],
  ['ksa-hegra-tomb-facade', 'Hegra Tomb Facade', 'Saudi Arabia'],
  ['ksa-historic-jeddah-roshan', 'Historic Jeddah Roshan', 'Saudi Arabia'],
  ['ksa-rijal-almaa-village', 'Rijal Almaa Village', 'Saudi Arabia'],
  ['ksa-marid-castle', 'Marid Castle', 'Saudi Arabia'],
  ['ksa-hima-rock-art', 'Hima Rock Art', 'Saudi Arabia'],
  ['ksa-elephant-rock', 'Elephant Rock', 'Saudi Arabia'],
  ['ksa-jabal-tuwaiq', 'Jabal Tuwaiq', 'Saudi Arabia'],
  ['ksa-empty-quarter-dunes', 'Empty Quarter Dunes', 'Saudi Arabia'],
  ['ksa-al-ahsa-oasis', 'Al-Ahsa Oasis', 'Saudi Arabia'],
  ['ksa-asir-al-soudah', 'Asir & Al-Soudah', 'Saudi Arabia'],
  ['ksa-red-sea-coral', 'Red Sea Coral', 'Saudi Arabia'],
  ['ksa-al-qarah-mountain', 'Al-Qarah Mountain', 'Saudi Arabia'],
  ['ksa-kingdom-centre', 'Kingdom Centre', 'Saudi Arabia'],
  ['ksa-al-faisaliah-tower', 'Al Faisaliah Tower', 'Saudi Arabia'],
  ['ksa-kafd-skyline', 'KAFD Skyline', 'Saudi Arabia'],
  ['ksa-ithra-cultural-centre', 'Ithra Cultural Centre', 'Saudi Arabia'],
  ['ksa-king-fahd-fountain', 'King Fahd Fountain', 'Saudi Arabia'],
  ['ksa-maraya-alula', 'Maraya, AlUla', 'Saudi Arabia'],
  ['ksa-saudi-coffee-dallah', 'Saudi Coffee Dallah', 'Saudi Arabia'],
  ['ksa-dates-date-palm', 'Dates & Date Palm', 'Saudi Arabia'],
  ['ksa-arabian-camel', 'Arabian Camel', 'Saudi Arabia'],
  ['ksa-saudi-falcon', 'Saudi Falcon', 'Saudi Arabia'],
  ['ksa-makkah-masjid-al-haram-kaaba', 'Makkah: Masjid Al-Haram & Kaaba', 'Saudi Arabia'],
  ['ksa-madinah-prophets-mosque', "Madinah: The Prophet's Mosque", 'Saudi Arabia'],
  ['ksa-map-13-regions', 'Saudi Map & 13 Regions', 'Saudi Arabia'],
  ['ksa-ardah-swords-drum', 'Saudi Ardah: Swords & Drum', 'Saudi Arabia'],
  ['ksa-traditional-najdi-door', 'Traditional Najdi Door', 'Saudi Arabia'],
  ['ksa-makkah-clock-tower', 'Makkah Clock Tower', 'Saudi Arabia'],
  ['ksa-taif-rose', 'Taif Rose', 'Saudi Arabia'],
  ['ksa-arabian-horse', 'Arabian Horse', 'Saudi Arabia'],
  ['ksa-arabian-leopard', 'Arabian Leopard', 'Saudi Arabia'],
  ['ksa-wadi-al-disah', 'Wadi Al-Disah', 'Saudi Arabia'],
  ['ksa-boulevard-world', 'Boulevard World', 'Saudi Arabia'],
  ['ksa-riyadh-metro', 'Riyadh Metro', 'Saudi Arabia'],
  ['ksa-qiddiya-city-stadium', 'Qiddiya City Stadium', 'Saudi Arabia'],
  ['ksa-new-murabba-mukaab', 'New Murabba: The Mukaab', 'Saudi Arabia'],
  ['ksa-world-cup-2034', 'Saudi Arabia 2034 World Cup', 'Saudi Arabia'],
  ['bahrain-qalat-al-bahrain', "Qal'at Al-Bahrain", 'Bahrain'],
  ['bahrain-bab-al-bahrain', 'Bab Al Bahrain', 'Bahrain'],
  ['bahrain-arad-fort', 'Arad Fort', 'Bahrain'],
  ['bahrain-pearling-path-bu-maher', 'Pearling Path & Bu Maher Fort', 'Bahrain'],
  ['bahrain-al-fateh-grand-mosque', 'Al Fateh Grand Mosque', 'Bahrain'],
  ['bahrain-al-khamis-mosque', 'Al Khamis Mosque', 'Bahrain'],
  ['bahrain-world-trade-center', 'Bahrain World Trade Center', 'Bahrain'],
  ['bahrain-international-circuit', 'Bahrain International Circuit', 'Bahrain'],
  ['bahrain-national-museum', 'Bahrain National Museum', 'Bahrain'],
  ['bahrain-tree-of-life', 'Tree of Life', 'Bahrain'],
].map(([id, name, country], index) => ({
  id,
  name,
  country,
  reference: `${country === 'Saudi Arabia' ? 'K' : 'B'}${String(country === 'Saudi Arabia' ? index + 1 : index - 39).padStart(2, '0')}`,
}));

export function findLandmarkScanItem(id) {
  return LANDMARK_SCAN_CATALOG.find((item) => item.id === id);
}

export function findLandmarkScanReference(reference) {
  const normalized = String(reference || '').toUpperCase();
  return LANDMARK_SCAN_CATALOG.find((item) => item.reference === normalized);
}
