-- Ministry Meeting portal — run ONCE in Supabase → SQL Editor → New query → Run.
-- Creates the portal's tables in the public schema (prefixed mm_). Safe to
-- re-run (IF NOT EXISTS). The 40 catalog items auto-seed on first portal visit.

create table if not exists public.mm_ministries (
    id bigint generated by default as identity primary key,
    name text not null,
    name_ar text,
    token text not null unique,
    contact_email text,
    contact_phone text,
    attention_name text,
    attention_title text,
    po_box text,
    internal_note text,
    created_at timestamptz not null default now()
);

create table if not exists public.mm_ministry_notes (
    id bigint generated by default as identity primary key,
    ministry_id bigint not null references public.mm_ministries(id) on delete cascade,
    note text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table if not exists public.mm_catalog_items (
    id bigint generated by default as identity primary key,
    item_no integer not null,
    name text not null,
    description text,
    category text not null,
    default_qty integer not null default 1,
    qty_fixed boolean not null default false,
    unit text,
    unit_price_fils integer not null,
    sort_order integer not null,
    active boolean not null default true
);

create table if not exists public.mm_quotations (
    id bigint generated by default as identity primary key,
    ministry_id bigint not null references public.mm_ministries(id),
    ref text not null,
    event_name text,
    venue text,
    event_date text,
    duration text,
    revision integer not null default 1,
    notes text,
    status text not null default 'submitted',
    subtotal_fils integer not null,
    vat_fils integer not null,
    total_fils integer not null,
    pdf_blob_url text,
    created_at timestamptz not null default now()
);

create table if not exists public.mm_quotation_lines (
    id bigint generated by default as identity primary key,
    quotation_id bigint not null references public.mm_quotations(id),
    item_id bigint,
    item_no integer not null,
    name_snapshot text not null,
    unit_price_fils_snapshot integer not null,
    qty integer not null,
    line_total_fils integer not null
);

create table if not exists public.mm_ministry_photos (
    id bigint generated by default as identity primary key,
    ministry_id bigint not null references public.mm_ministries(id),
    blob_url text not null,
    pathname text,
    caption text,
    uploaded_at timestamptz not null default now()
);
